//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Common {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ApiErrors {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ApiErrors() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Common.ApiErrors", typeof(ApiErrors).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Token cannot be generated.
        /// </summary>
        internal static string _0001_DESCRIPTION {
            get {
                return ResourceManager.GetString("0001_DESCRIPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please verify credentials in the request.
        /// </summary>
        internal static string _0001_SOLUTION {
            get {
                return ResourceManager.GetString("0001_SOLUTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User is already registered with same username/email .
        /// </summary>
        internal static string _0002_DESCRIPTION {
            get {
                return ResourceManager.GetString("0002_DESCRIPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If you are an existing user, please login. If new user then consider registering with a different username/email.
        /// </summary>
        internal static string _0002_SOLUTION {
            get {
                return ResourceManager.GetString("0002_SOLUTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Provided payer id is not a valid user id..
        /// </summary>
        internal static string _0003_DESCRIPTION {
            get {
                return ResourceManager.GetString("0003_DESCRIPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please verify and provide a correct user id as payer id.
        /// </summary>
        internal static string _0003_SOLUTION {
            get {
                return ResourceManager.GetString("0003_SOLUTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Provided payee id is not a valid user id..
        /// </summary>
        internal static string _0004_DESCRIPTION {
            get {
                return ResourceManager.GetString("0004_DESCRIPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please verify and provide a correct user id as payee id.
        /// </summary>
        internal static string _0004_SOLUTION {
            get {
                return ResourceManager.GetString("0004_SOLUTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The amount provided in the expense is not a valid amount.
        /// </summary>
        internal static string _0005_DESCRIPTION {
            get {
                return ResourceManager.GetString("0005_DESCRIPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expense amount cannot be less than 1.
        /// </summary>
        internal static string _0005_SOLUTION {
            get {
                return ResourceManager.GetString("0005_SOLUTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creating of expense was unsuccessful.
        /// </summary>
        internal static string _0006_DESCRIPTION {
            get {
                return ResourceManager.GetString("0006_DESCRIPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please provide correct data to process expense request successfully..
        /// </summary>
        internal static string _0006_SOLUTION {
            get {
                return ResourceManager.GetString("0006_SOLUTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0006:Cannot create expense.
        /// </summary>
        internal static string err_add_expense_failure {
            get {
                return ResourceManager.GetString("err_add_expense_failure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0005:Invalid expense amount.
        /// </summary>
        internal static string err_invalid_expense_amount {
            get {
                return ResourceManager.GetString("err_invalid_expense_amount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0004:Invalid payee id.
        /// </summary>
        internal static string err_invalid_payee_id {
            get {
                return ResourceManager.GetString("err_invalid_payee_id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0003:Invalid payer id.
        /// </summary>
        internal static string err_invalid_payer_id {
            get {
                return ResourceManager.GetString("err_invalid_payer_id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0001:Token generation failed.
        /// </summary>
        internal static string err_token_generation_failed {
            get {
                return ResourceManager.GetString("err_token_generation_failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0002:User already exists.
        /// </summary>
        internal static string err_user_exists {
            get {
                return ResourceManager.GetString("err_user_exists", resourceCulture);
            }
        }
    }
}
